package by.htp.store.controller.command;

public enum CommandName {

	SIGN_IN, 
	REGISTRATION,
	SUBCATEGORY,
	GROUP_PRODUCT_BY_SUBCATEGORY,
	GO_TO_PRODUCT_INFO,
	ADD_REVIEW_TO_PRODUCT,
	WRONG_REQUEST,
	GO_TO_ERROR_PAGE, 
	GO_TO_SIGN_IN,
	GO_TO_REGISTRATION,
	GO_TO_MAIN,
	ADD_PRODUCT_FAVORITES,
	DELETE_PRODUCT_FAVORITES,
	FAVORITES,
	ADD_TO_CART,
	GO_TO_CART,
	DELETE_PRODUCT_IN_CART,
	SIGN_OUT,
	GROUP_PRODUCT_MANUFACTURER,
	USER_PROFILE,
	CHANGE_USER_INFO,
	CHECKOUT,
	ORDER_HISTORY,
	GO_TO_ORDER_INFO,
	DELETE_REVIEW_PRODUCT,
	CHANGE_LOCAL,
	SEARCH_PRODUCT;

	

	

}
